# This rule is not used by the project configmirror-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over mirror.configmirror.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: configmirror-operator
    app.kubernetes.io/managed-by: kustomize
  name: configmirror-admin-role
rules:
- apiGroups:
  - mirror.configmirror.io
  resources:
  - configmirrors
  verbs:
  - '*'
- apiGroups:
  - mirror.configmirror.io
  resources:
  - configmirrors/status
  verbs:
  - get
