---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mirror.configmirror.io
  resources:
  - configmirrors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mirror.configmirror.io
  resources:
  - configmirrors/finalizers
  verbs:
  - update
- apiGroups:
  - mirror.configmirror.io
  resources:
  - configmirrors/status
  verbs:
  - get
  - patch
  - update
