apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "configmirror-operator.fullname" . }}-manager-role
  labels:
    {{- include "configmirror-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mirror.configmirror.io
  resources:
  - configmirrors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mirror.configmirror.io
  resources:
  - configmirrors/finalizers
  verbs:
  - update
- apiGroups:
  - mirror.configmirror.io
  resources:
  - configmirrors/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "configmirror-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "configmirror-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "configmirror-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "configmirror-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "configmirror-operator.fullname" . }}-leader-election-role
  labels:
    {{- include "configmirror-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "configmirror-operator.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "configmirror-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "configmirror-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "configmirror-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
